name: Django CI

on:
  push:
    branches: [ master ]
    paths:
      - "Django/**"

jobs:
  Django:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build ./Django --tag ken109/django:latest
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push
      run: docker push ken109/django:latest
