name: DNS Server CI

on:
  push:
    branches: [ master ]
    paths:
      - "DNSServer/**"

  schedule:
    - cron: '0 0 */5 * *'

jobs:
  DNSServer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build ./DNSServer --tag ken109/dns:latest
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push
      run: docker push ken109/dns:latest
