name: Docker Image CI

on:
  push:
    branches: [ master ]

  schedule:
    - cron: '0 0 */5 * *'

jobs:
  Laravel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build ./Laravel --tag ken109/laravel:latest
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push
      run: docker push ken109/laravel:latest
  
  DNSServer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build ./DNSServer --tag ken109/dns:latest
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push
      run: docker push ken109/dns:latest
  
  Django:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build ./Django --tag ken109/django:latest
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push
      run: docker push ken109/django:latest
