name: Laravel CI

on:
  push:
    branches: [ master ]
    paths:
      - "Laravel/**"

  schedule:
    - cron: '0 0 */5 * *'

jobs:
  Laravel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build ./Laravel --tag ken109/laravel:latest
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push
      run: docker push ken109/laravel:latest
